set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME WASI)
set(VCPKG_CMAKE_SYSTEM_VERSION 1)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR wasm32)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../../wasi-sdk/wasi-sdk.toolchain.cmake")
