name: "Vcpkg binary cache + GitHub Actions cache"


runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Set vcpkg binary source
      shell: bash
      run: |
        echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> ${GITHUB_ENV}
