name: "Ubuntu wasm32 dependencies"

runs:
  using: "composite"
  steps:
    - name: Download wasm32 libclang runtime
      shell: bash
      run: |
        sudo mkdir -p "$(clang --print-resource-dir)"
        sudo wget -c \
          https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-21/libclang_rt.builtins-wasm32-wasi-21.0.tar.gz \
          -O - | sudo tar -xzf - -C "$(clang --print-resource-dir)"
