name: ci

on: [pull_request]

jobs:
  build:
    runs-on: ${{matrix.target.os}}
    strategy:
      fail-fast: false
      matrix:
        target: [
          { os: ubuntu-22.04, preset: wasm32-wasi-clang-static },
          { os: ubuntu-latest, preset: x64-linux-gcc-dynamic },
          { os: ubuntu-latest, preset: x86-linux-gcc-dynamic },
          { os: ubuntu-latest, preset: x64-linux-clang-dynamic },
          { os: ubuntu-latest, preset: x86-linux-clang-dynamic },
          { os: macos-latest, preset: x64-darwin-gcc-dynamic },
          { os: macos-latest, preset: x64-darwin-clang-dynamic },
          { os: windows-latest, preset: x64-windows-msvc-dynamic },
          { os: windows-latest, preset: x64-windows-clang-dynamic },
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Init template
      shell: bash
      run: |
        cmake -P init.cmake --project gat --module core --header version

    - uses: ./.github/actions/install-dependencies
      with:
        preset: ${{matrix.target.preset}}

    - uses: ./.github/actions/vcpkg-cache

    - name: CMake workflow
      id: cmake-workflow
      shell: bash
      run: |
        cmake --workflow --preset ${{matrix.target.preset}}

    - name: Upload vcpkg error logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{matrix.target.preset}}
        path: |
          /usr/local/share/vcpkg/**/*.log
